name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/README.md"

jobs:
  unit-test:
    name: Unit Test
    runs-on: macos-14
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Test
        working-directory: ShiftWindowPackages
        run: |
          xcodebuild test \
            -scheme ShiftWindowPackages-Package \
            -destination "platform=macOS,arch=arm64" \
            -resultBundlePath TestResults |\
            xcpretty -c && exit ${PIPESTATUS[0]}
